### PR TITLE
Requesting temperature value

### LINKED ISSUE #14: Requesting temperature values
Hi,
I'm using `homebridge-mqtt-temperature` to bridge the values published by my NodeMCU. Everything works fine but I'd like to be able to request the current temperature when Homekit asks for it. 

The background is that my sensor publishes the temp reading every 2h. If I start homebridge, it can take up to 2h for the temperature to become available in `homebridge-mqtt-temperature`

The solution could be as simple as defining and publishing a topic in the `TemperatureAccessory.prototype.getState` to which the sensor should react.

I'm aware that the actual temperature result might be immediately available to the homebridge callback but at least the temperature cached for the next time the homebridge requests it.

### PR DESCRIPTION
**Pull request by JanC**
fixes #14

### CODE REVIEW

**Comment by mcchots** [comment]
From my testing, you're not handling conditions where ``topic_get`` is not used/required. I fail to get any results. Right now it's not an optional feature.

**Comment by JanC** [comment]
yes you are right. The callback needs to be called when the `topic_get` is not supplied. Fixed

**Comment by JanC** [comment]
thanks for accepting this ;)

**Comment by mcchots** [comment]
No problem. It's a worthwhile feature. I'll only be able to update the npm repo this evening or tomorrow though.

**Pull request merged**
